/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frontend;

/**
 *
 * @author Andre Kurniawan
 */
public class FrmMenu extends javax.swing.JFrame {

    /**
     * Creates new form FrmMenu
     */
    public FrmMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        mMaster = new javax.swing.JMenu();
        mFrmKategori = new javax.swing.JMenuItem();
        mFrmBuku = new javax.swing.JMenuItem();
        mFrmAnggota = new javax.swing.JMenuItem();
        tTransaksi = new javax.swing.JMenu();
        TFromTransaksi = new javax.swing.JMenuItem();
        Menu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mMaster.setText("Master");

        mFrmKategori.setText("Frm Kategori");
        mFrmKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mFrmKategoriActionPerformed(evt);
            }
        });
        mMaster.add(mFrmKategori);

        mFrmBuku.setText("Frm Buku");
        mFrmBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mFrmBukuActionPerformed(evt);
            }
        });
        mMaster.add(mFrmBuku);

        mFrmAnggota.setText("Frm Anggota");
        mFrmAnggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mFrmAnggotaActionPerformed(evt);
            }
        });
        mMaster.add(mFrmAnggota);

        jMenuBar1.add(mMaster);

        tTransaksi.setText("Transaksi");

        TFromTransaksi.setText("Peminjaman");
        TFromTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFromTransaksiActionPerformed(evt);
            }
        });
        tTransaksi.add(TFromTransaksi);

        jMenuBar1.add(tTransaksi);

        Menu.setText("Menu");
        jMenuBar1.add(Menu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TFromTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFromTransaksiActionPerformed
        // TODO add your handling code here:
        FrmPeminjaman frmPeminjaman = new FrmPeminjaman();
        frmPeminjaman.setVisible(true);
    }//GEN-LAST:event_TFromTransaksiActionPerformed

    private void mFrmKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mFrmKategoriActionPerformed
        // TODO add your handling code here:
        FrmKategori frmKategori = new FrmKategori();
        frmKategori.setVisible(true);
    }//GEN-LAST:event_mFrmKategoriActionPerformed

    private void mFrmBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mFrmBukuActionPerformed
        // TODO add your handling code here:
        FrmBuku frmBuku = new FrmBuku();
        frmBuku.setVisible(true);
    }//GEN-LAST:event_mFrmBukuActionPerformed

    private void mFrmAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mFrmAnggotaActionPerformed
        // TODO add your handling code here:
        FrmAnggota frmAnggota = new FrmAnggota();
        frmAnggota.setVisible(true);
    }//GEN-LAST:event_mFrmAnggotaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Menu;
    private javax.swing.JMenuItem TFromTransaksi;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mFrmAnggota;
    private javax.swing.JMenuItem mFrmBuku;
    private javax.swing.JMenuItem mFrmKategori;
    private javax.swing.JMenu mMaster;
    private javax.swing.JMenu tTransaksi;
    // End of variables declaration//GEN-END:variables
}
